# Generated by Django 5.1.2 on 2024-12-10 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('callerID', models.AutoField(primary_key=True, serialize=False)),
                ('callerName', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('LGBTQ++', 'LGBTQ++'), ('N/A', 'N/A')], max_length=255, null=True)),
                ('civilStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Single (Living in)', 'Single (Living in)'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('N/A', 'N/A')], max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=2, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('infoSource', models.CharField(blank=True, choices=[('Online', 'Online'), ('Media', 'Media'), ('Family/Friend', 'Family/Friend'), ('Colleague', 'Colleague'), ('Referral', 'Referral')], max_length=255, null=True)),
                ('callerType', models.CharField(blank=True, choices=[('Mental Health', 'Mental Health'), ('Marital', 'Marital'), ('School', 'School'), ('Financial', 'Financial'), ('Suicidal Crisis', 'Suicidal Crisis'), ('Calling for another person', 'Calling for another person')], max_length=255, null=True)),
                ('intervention', models.CharField(blank=True, choices=[('PsychEducation', 'PsychEducation'), ('Referral', 'Referral'), ('Empathetic Listening', 'Empathetic Listening'), ('Breathing Technique', 'Breathing Technique')], max_length=255, null=True)),
                ('riskAssessment', models.CharField(blank=True, choices=[('Low Risk', 'Low Risk'), ('Moderate Risk', 'Moderate Risk'), ('High Risk', 'High Risk')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('responderID', models.AutoField(primary_key=True, serialize=False)),
                ('responderName', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='form.caller')),
            ],
        ),
        migrations.CreateModel(
            name='AITranscript',
            fields=[
                ('transcriptID', models.AutoField(primary_key=True, serialize=False)),
                ('transcriptSummary', models.CharField(max_length=255)),
                ('generatedTimestamp', models.DateTimeField()),
                ('transcriptFeedback', models.CharField(max_length=255)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='form.callsession')),
            ],
        ),
        migrations.CreateModel(
            name='MHealthData',
            fields=[
                ('mhealthID', models.AutoField(primary_key=True, serialize=False)),
                ('crisisType', models.CharField(max_length=255)),
                ('suicidalityRisk', models.CharField(max_length=255)),
                ('selfHarmingMethod', models.CharField(max_length=255)),
                ('call_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mhealth_data', to='form.callsession')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('representativeID', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=255)),
                ('patientRelationship', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='form.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('dateGenerated', models.DateField()),
                ('reportType', models.CharField(max_length=255)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='form.responder')),
            ],
        ),
        migrations.CreateModel(
            name='CallerHistory',
            fields=[
                ('callerhistoryID', models.AutoField(primary_key=True, serialize=False)),
                ('endTime', models.DateTimeField()),
                ('notes', models.CharField(max_length=255)),
                ('outcome', models.CharField(max_length=255)),
                ('mhealthData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.mhealthdata')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.responder')),
            ],
        ),
    ]
