# Generated by Django 5.1.5 on 2025-01-28 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_referralcontact_email_referralcontact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='callDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
