# Generated by Django 5.1.5 on 2025-02-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_callsession_responder_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller',
            old_name='callerType',
            new_name='reason',
        ),
    ]
