# Generated by Django 5.1.5 on 2025-02-25 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_rename_callertype_caller_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callers', to='form.patient'),
        ),
        migrations.AddField(
            model_name='caller',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callers', to='form.representative'),
        ),
    ]
