# Generated by Django 5.1.5 on 2025-02-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_caller_patient_caller_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
